### ISSUE TITLE
gulp e2e is no longer passing Travis due to ObjectPath

### ISSUE THREAD

**Issue by pauleveritt** [MoonshotProject/moondash#58]
In fact, I don't think the setup works correctly now even locally. My attempt at firing up a browserSync:e2e task running on port 3001 might not be working well.

**Comment by ebrehault** [comment]
Fixed by https://github.com/MoonshotProject/moondash/commit/6ceae4a5e14cfc15b32aed7a5d7705b4b896a6e1
