### ISSUE TITLE
dist should produce sourcemap file for moondash.js

### ISSUE THREAD

**Issue by pauleveritt** [MoonshotProject/moondash#60]
We currently generate the sourcemap and inline it at the end of the file. This makes what should be a 90k file into a 230k file. Change this to generate a source map file.

**Comment by pauleveritt** [comment]
I just did gulp —dist —mock and saw that dist/moondash-vendors-with-mock.js is double the size of without mocks. That’s surprising. I guess the url package is big.

Not a big deal.

—Paul

**Comment by pauleveritt** [comment]
build/moondash-vendors.js ends with this:

//# sourceMappingURL=maps/moondash.js.map

...which is correct, but build/moondash.js ends with this:

//# sourceMappingURL=moondash.js.map

..which is missing "maps/"

**Comment by ebrehault** [comment]
Fixed with https://github.com/MoonshotProject/moondash/commit/5c42c26bcb86a59a860009a8829c67f6d6d3b197
